<?php
if ( ! defined( 'ABSPATH' ) ) exit;

delete_option( 'gs_form_phone');
delete_option('gs_form_rand_time');
delete_option('gs_form_rand_proc');
delete_option( 'gs_form_admin_email');
delete_option( 'gs_form_email_message');
delete_option( 'gs_form_main_color');
delete_option( 'gs_form_accent_color');
delete_option( 'gs_form_t_email');
delete_option( 'gs_form_t_name');
delete_option( 'gs_form_t_lastname');
delete_option( 'gs_form_t_phone');
delete_option( 'gs_form_static1_1_title');
delete_option( 'gs_form_static1_1_subtitle');
delete_option( 'gs_form_static1_1_button');
delete_option( 'gs_form_static1_2_title');
delete_option( 'gs_form_static1_2_subtitle');
delete_option( 'gs_form_static1_2_after');
delete_option( 'gs_form_static1_3_title');
delete_option( 'gs_form_static1_3_before');
delete_option( 'gs_form_static1_3_after');
delete_option( 'gs_form_static1_3_button');
delete_option( 'gs_form_static1_4_title');
delete_option( 'gs_form_static1_4_button');
delete_option( 'gs_form_last_title');
delete_option( 'gs_form_last_subtitle');
delete_option( 'gs_form_last_1');
delete_option( 'gs_form_last_2');
delete_option( 'gs_form_last_3');
delete_option( 'gs_form_last_before');
delete_option( 'gs_form_last_after');
delete_option( 'gs_form_static2_1_title');
delete_option( 'gs_form_static2_1_subtitle');
delete_option( 'gs_form_static2_1_button');
delete_option( 'gs_form_static2_2_title');
delete_option( 'gs_form_static2_2_steps');
delete_option( 'gs_form_static2_2_button');
delete_option( 'gs_form_admin_locale' );
